### ISSUE TITLE
Getting 400 error

### ISSUE THREAD

**Issue by choiman1559** [FirebaseExtended/auth-without-play-services#11]
Getting 400 error when sign in.
every sign in action get such error.

the log below is a copy of the exception thrown by the sample app of this repo.
```
 2020-08-09 01:39:06.895 32294-32294/com.google.firebase.nongmsauth D/RestAuthProvider: currentUser = null
2020-08-09 01:39:06.898 32294-32294/com.google.firebase.nongmsauth W/MainActivity: signInAnonymously: failure
    java.lang.Exception: Body null, status code 400
        at com.google.firebase.nongmsauth.utils.RetrofitUtils$Companion$callToTask$1.onResponse(RetrofitUtils.kt:39)
        at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0$DefaultCallAdapterFactory$ExecutorCallbackCall$1(DefaultCallAdapterFactory.java:89)
        at retrofit2.-$$Lambda$DefaultCallAdapterFactory$ExecutorCallbackCall$1$3wC8FyV4pyjrzrYL5U0mlYiviZw.run(Unknown Source:6)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:915)
```

**Comment by choiman1559** [comment]
Caused by a configuration mistake in Firebase.
